<?php
define('THIS_IS_SOMEWHAT',__('This is somewhat embarrassing, isn&rsquo;t it?','harrington'));
define('IT_SEEMS_WE',__('It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the links below, can help.', 'harrington'));
define('MOST_USED_CATEGORIES',__('Most Used Categories', 'harrington'));
define('MONTHLY_ARCHIVES',__('Try looking in the monthly archives. %1$s', 'harrington'));
define('SORRY_NO_POST_MATCHED',__('Sorry, no posts matched your criteria.', 'harrington'));
define('NOTHING_FOUND',__('Nothing Found here', 'harrington'));
define('NOTHING_MATCHED',__('Sorry, but nothing matched your search criteria.', 'harrington'));
define('CATEGORIES',__('Categories', 'harrington'));
define('ARCHIVES',__('Archives', 'harrington'));
define('BLOG_ARCHIVES',__('Blog Archives', 'harrington'));
define('CATEGORY_ARCHIVES',__('Category Archives: %s', 'harrington'));
define('PAGE',__('Page %s', 'harrington'));
define('SEARCH_RESULT',__('Search Results for: %s', 'harrington'));
define('TAG_ARCHIVES',__('Tag Archives: %s', 'harrington'));
define('DAILY_ARCHIVES',__('Daily Archives: %s', 'harrington'));
define('LCN_MAP',__('Location Map','harrington'));
define('YEARLY_ARCHIVES',__('Yearly Archives: %s', 'harrington'));
define('AUTHOR_ARCHIVES',__('Author Archives: %s', 'harrington'));
define('ABOUT',__('About: %s', 'harrington'));
define('HOME_TEXT',__('Home', 'harrington'));
define('THIS_ENTRY_WAS_POSTED_IN',__('This entry was posted in %1$s','harrington'));
define('PERMALINK',__('permalink','harrington'));
define('BOOKMARK_THE',__('Bookmark the','harrington'));
define('PRIMARY_WIDGET',__('Primary Widget Area', 'harrington'));
define('THE_PRIMARY_WIDGET',__('The primary widget area', 'harrington'));
define('SECONDRY_WIDGET',__('Secondary Widget Area', 'harrington'));
define('THE_SECONDRY_WIDGET',__('The secondary widget area', 'harrington'));
define('SMT_CMT',__('submit Comment', 'harrington'));
define('LV_CMT',__('Leave a Comment', 'harrington'));
define('FIRST_FOOTER_WIDGET',__('First Footer Widget Area', 'harrington'));
define('THE_FIRST_FOOTER_WIDGET',__('The first footer widget area', 'harrington'));
define('SECONDRY_FOOTER_WIDGET',__('Second Footer Widget Area', 'harrington'));
define('THE_SECONDRY_FOOTER_WIDGET',__('The second footer widget area', 'harrington'));
define('THIRD_FOOTER_WIDGET',__('Third Footer Widget Area', 'harrington'));
define('THE_THIRD_FOOTER_WIDGET',__('The third footer widget area', 'harrington'));
define('FOURTH_FOOTER_WIDGET',__('Fourth Footer Widget Area', 'harrington'));
define('THE_FOURTH_FOOTER_WIDGET',__('The fourth footer widget area', 'harrington'));
define('OLDER_POSTS',__('&larr; Older posts', 'harrington'));
define('NEWER_POSTS',__('Newer posts &rarr;', 'harrington'));
define('PREV_POST',__(' Previous Post', 'harrington'));
define('NEXT_POST',__('Next Post ', 'harrington'));
define('READ_MORE',__('Read More', 'harrington'));
define('SND_MSG',__('Send Your Message', 'harrington'));
define('RETURN_TO',__('Return to %s', 'harrington'));
define('BY_AUTHOR',__('By %2$s', 'harrington'));
define('VIEW_ALL_POST_BY',__('View all posts by %s', 'harrington'));
define('PUBLISHED_BY',__('Published %2$s', 'harrington'));
define('FULL_SIZE_IS_PIXEL',__('Full size is %s pixels', 'harrington'));
define('LINK_TO_FULL_SIZE_IMAGE',__('Link to full-size image', 'harrington'));
define('EDIT_TEXT',__('Edit', 'harrington'));
define('CONTINUE_READING',__('Continue reading &rarr;', 'harrington'));
define('PAGES_COLON',__('Pages:', 'harrington'));
define('CONTINUE_READING_DOTS',__('Read More', 'harrington'));
define('POSTED_BY',__('Posted by', 'harrington'));
define('AND_TAGGED',__('and tagged','harrington'));
define('SMT_MSG',__('Submit Message','harrington'));
define('POST_TAGGED_WITH', __('Post Tagged with','harrington'))
?>